root = "."
tmp_dir = ".tmp"

[build]
cmd = "go build -o ./.tmp/api ./cmd/api"
entrypoint = ["./.tmp/api"]
include_ext = ["go", "sql"]
include_file = ["go.mod", "go.sum"]
exclude_dir = [".tmp", "vendor"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = false
poll = true
poll_interval = 500
delay = 500
stop_on_error = true
send_interrupt = true

[log]
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
